### ISSUE TITLE
Modelo relatório 

### ISSUE THREAD

**Issue by klnlopes** [klnlopes/Hello-World#32]
### PMO Request link

https://github.com/github/Revenue-PMO/issues/196

### OAR link

Services Evolution - Create a sustainable and resilient services delivery model that focuses on high value output

### Introduction

As GitHub's reach and revenue continue to grow, our GitHub Offerings Team have been focused on evolving our GitHub Services Offering portfolio to build offerings that are more transformational in nature opposed to workshops and trainings that has been the focus initially.

Offerings are key to define how Expert Services brings value to GitHub and moving towards transformational offerings enables Expert Services to be a strategic differentiator for GitHub and support our Revenue colleagues on enabling customers to go all in on GitHub.

### Objectives

This program is currently divided into 2 projects: 

- Epic 1 [MSFT Product Innovation Development Services (PIDs) Integration](https://github.com/github/Offerings-Evolution-Project/issues/3)

Implement current PEX offerings into MSFT Product Innovation Development Services (PIDs)

- Epic 2 https://github.com/github/Offerings-Evolution-Project/issues/1

A transformational deal / offering is a large umbrella offering with various GitHub packages / modules within. In turn, the term transformational becomes the vehicle and narrative to sell a suite of GitHub offerings in one deal at higher levels in the customer's organisation, typically targeting Technology decision makers. Centred on a DevOps narrative, a transformational offering tackles the change management necessary to land technological change and subsequently offerings that make that happen.

### Success Criteria and Impact Metrics

Epic 1:

```[tasklist]
### Success Criteria Epic 1 
- [ ] Validate actual pipeline opportunity against expectations
- [ ] Identify and execute against at least 1 pilot opportunity in the presales stage and document the process. (phase 1)
- [ ] Deliver against at least 1 pilot PIDs services engagement jointly with MSFT counterparts. (phase 2)
- [ ] Assess operating model &  BAU viability of this joint collaboration 

```

Epic 2:

```[tasklist]
### Success Criteria Epic 2
- [ ] Attainment or direct correlation to increase in Services Bookings $
- [ ] Attainment or direct correlation to increase in Services Inclusion rate
- [ ] Attainment or direct correlation to increase in Services Attach rate
- [ ] Correlation to increase in Consumption revenue dollars for customers with vs customers without services
- [ ] Correlation to Contractions rates for customers with vs customers without services

```

### Program Dates

- **Start Date**: 11/09/2024
- **End Date**: 06/30/2024
- **Program Hand-off**: TBD

### Program Team

Lead(s) | Role & Responsibilities| Epic |
|----|----|----|
| @claudiabout | DRI Epic 1 - Sr. Manager, MSFT GTM - Services & Partner | Epic 1 |
| @ppremk | DRI Epic 2 - Director Expert Services Offerings | Epic 1/2 |
| @jackwillrawl | Senior Business Operations Manager | Epic 1/2 |
| @amelietonneau | PM, Senior Business Program Manager | Epic 1/2 |
| @juanjocarmena | Entreprise Solutions Sales Manager EMEA | Epic 1 |
| @Msanzdelrio | Technical Partner Manager | Epic 1 |
| @umatty | Director Expert Services | Epic 1/2 |
| Camilla Giudes | MSFT Project Manager | Epic 1 |
| @smayoharison | C-PEX Consultant | Epic 2 | 

<br class="Apple-interchange-newline">

**General Program Team Responsibilities:**
- Provide visibility to work / deliverables that the workstream will deliver for the program
- Partner with the PM to identify cross functional dependencies
- Provide weekly status on area deliverables, risks, and mitigation plans to the PM

### Risks and Dependencies

Coming soon

### Milestones and Deliverables

Coming soon
| Key Milestones | Date | Milestone Link | 
|--------|--------|--------|
|--- |**mm/dd/yy**|--- |
|--- |**mm/dd/yy**|--- |
|--- |**mm/dd/yy**|--- |
|--- |**mm/dd/yy**|--- |

### Program Plan

Coming soon

### Communication Plan

- **Repository:** https://github.com/github/Offerings-Evolution-Project/
- **Issue updates:** #revenue-pmo-reporting
- **Internal Private Slack channel:** #gh-msft-pids (Epic 1) & devx-transformation-services (Epic 2)
- **Meeting Schedule:** Friday PIDs / TBD DevX
